-- Skyline-App database schema (MariaDB / MySQL, multi-tenant)
-- Run against your MariaDB database to build it from scratch.
-- WARNING: this script DROPS all existing app tables and their data.
--
-- Tenant isolation (formerly Postgres RLS) is enforced in the PHP API layer:
-- every query is scoped by company_id derived from the logged-in session.

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS generated_documents;
DROP TABLE IF EXISTS document_templates;
DROP TABLE IF EXISTS audit_logs;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS warranties;
DROP TABLE IF EXISTS vendor_pricing;
DROP TABLE IF EXISTS vendor_contacts;
DROP TABLE IF EXISTS chemicals;
DROP TABLE IF EXISTS vendors;
DROP TABLE IF EXISTS entity_project_types;
DROP TABLE IF EXISTS entity_contacts;
DROP TABLE IF EXISTS project_types;
DROP TABLE IF EXISTS leads;
DROP TABLE IF EXISTS loan_repayments;
DROP TABLE IF EXISTS loans;
DROP TABLE IF EXISTS lenders;
DROP TABLE IF EXISTS milestones;
DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS expense_items;
DROP TABLE IF EXISTS expenses;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS clients;
DROP TABLE IF EXISTS customer_accounts;
DROP TABLE IF EXISTS profiles;
DROP TABLE IF EXISTS companies;
DROP TABLE IF EXISTS password_resets;
DROP TABLE IF EXISTS users;

SET FOREIGN_KEY_CHECKS = 1;

-- ── Auth ─────────────────────────────────────────────────────────────────────
-- Replaces Supabase auth.users. UUIDs are generated by the PHP layer (v4).

CREATE TABLE users (
  id                   char(36)     NOT NULL,
  email                varchar(255) NOT NULL,
  password_hash        varchar(255) NOT NULL,
  active_login_ip      varchar(45)  DEFAULT NULL,
  active_session_token char(64)     DEFAULT NULL,
  session_last_seen    timestamp    NULL DEFAULT NULL,
  created_at           timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_users_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE password_resets (
  id         bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id    char(36)     NOT NULL,
  token_hash char(64)     NOT NULL,
  expires_at timestamp    NOT NULL,
  created_at timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_password_resets_token (token_hash),
  KEY idx_password_resets_user  (user_id),
  CONSTRAINT fk_password_resets_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── Tenancy ──────────────────────────────────────────────────────────────────

-- A company is a tenant. Every business row is scoped to one company.
CREATE TABLE companies (
  id         char(36)     NOT NULL,
  name         varchar(255) NOT NULL,
  logo_path    varchar(255) DEFAULT NULL,
  favicon_path varchar(255) DEFAULT NULL,
  owner_id     char(36)     NOT NULL,
  created_at timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_companies_owner (owner_id),
  CONSTRAINT fk_companies_owner FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- One profile per user. role + is_active drive access.
CREATE TABLE profiles (
  id         char(36)     NOT NULL,
  company_id char(36)     DEFAULT NULL,
  role       varchar(20)  NOT NULL DEFAULT 'member',
  is_active  tinyint(1)   NOT NULL DEFAULT 1,
  full_name  varchar(255) DEFAULT NULL,
  email      varchar(255) DEFAULT NULL,
  created_at timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_profiles_company_id (company_id),
  CONSTRAINT fk_profiles_user    FOREIGN KEY (id)         REFERENCES users(id)     ON DELETE CASCADE,
  CONSTRAINT fk_profiles_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL,
  CONSTRAINT chk_profiles_role   CHECK (role IN ('super_admin', 'owner', 'member'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── Business tables ──────────────────────────────────────────────────────────

-- B2B customer organizations (NOT the Skyline tenant in `companies`).
CREATE TABLE customer_accounts (
  id         char(36)     NOT NULL,
  company_id char(36)     NOT NULL,
  name       varchar(255) NOT NULL,
  email      varchar(255) DEFAULT NULL,
  phone      varchar(50)  DEFAULT NULL,
  address    text         DEFAULT NULL,
  location   varchar(255) DEFAULT NULL,
  notes      text         DEFAULT NULL,
  created_at timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_customer_accounts_company_id (company_id),
  CONSTRAINT fk_customer_accounts_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- CRM contacts. B2C = individual; B2B = contact person at a customer_accounts row.
CREATE TABLE clients (
  id                  char(36)     NOT NULL,
  company_id          char(36)     NOT NULL,
  client_type         varchar(32)  NOT NULL DEFAULT 'b2c',
  customer_account_id char(36)     DEFAULT NULL,
  name                varchar(255) NOT NULL,
  contact_title       varchar(255) DEFAULT NULL,
  email               varchar(255) DEFAULT NULL,
  phone               varchar(50)  DEFAULT NULL,
  address             text         DEFAULT NULL,
  location            varchar(255) DEFAULT NULL,
  source              varchar(255) DEFAULT NULL,
  tags                json         DEFAULT NULL,
  notes               text         DEFAULT NULL,
  created_at          timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_clients_company_id (company_id),
  KEY idx_clients_customer_account_id (customer_account_id),
  CONSTRAINT fk_clients_company          FOREIGN KEY (company_id)          REFERENCES companies(id)          ON DELETE CASCADE,
  CONSTRAINT fk_clients_customer_account FOREIGN KEY (customer_account_id) REFERENCES customer_accounts(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE leads (
  id                   char(36)       NOT NULL,
  company_id           char(36)       NOT NULL,
  client_id            char(36)       DEFAULT NULL,
  contact_name         varchar(255)   DEFAULT NULL,
  project_title        varchar(255)   DEFAULT NULL,
  phone                varchar(50)    DEFAULT NULL,
  email                varchar(255)   DEFAULT NULL,
  location             varchar(255)   DEFAULT NULL,
  source               varchar(255)   DEFAULT NULL,
  status               varchar(40)    NOT NULL DEFAULT 'new_inquiry',
  estimated_value      decimal(12, 2) DEFAULT NULL,
  notes                text           DEFAULT NULL,
  converted_project_id char(36)       DEFAULT NULL,
  created_at           timestamp      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at           timestamp      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_leads_company_id (company_id),
  KEY idx_leads_client_id (client_id),
  KEY idx_leads_status (status),
  KEY idx_leads_converted_project (converted_project_id),
  CONSTRAINT fk_leads_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_leads_client  FOREIGN KEY (client_id)  REFERENCES clients(id)   ON DELETE SET NULL,
  CONSTRAINT chk_leads_status CHECK (status IN (
    'new_inquiry', 'photos_received', 'site_visit_scheduled',
    'quotation_pending', 'quotation_sent', 'converted', 'lost'
  ))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE projects (
  id                  char(36)       NOT NULL,
  company_id          char(36)       NOT NULL,
  client_id           char(36)       DEFAULT NULL,
  lead_id             char(36)       DEFAULT NULL,
  project_title       varchar(255)   NOT NULL,
  client_name         varchar(255)   DEFAULT NULL,
  location            varchar(255)   DEFAULT NULL,
  work_description    text           DEFAULT NULL,
  total_quoted_amount decimal(12, 2) DEFAULT NULL,
  amount_received     decimal(12, 2) DEFAULT 0,
  status              varchar(40)    NOT NULL DEFAULT 'site visit requested',
  completion_percent  int            DEFAULT 0,
  start_date          date           DEFAULT NULL,
  end_date            date           DEFAULT NULL,
  created_at          timestamp      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_projects_company_id (company_id),
  KEY idx_projects_client_id  (client_id),
  KEY idx_projects_lead_id    (lead_id),
  KEY idx_projects_status     (status),
  KEY idx_projects_start_date (start_date),
  CONSTRAINT fk_projects_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_projects_client  FOREIGN KEY (client_id)  REFERENCES clients(id)   ON DELETE SET NULL,
  CONSTRAINT fk_projects_lead    FOREIGN KEY (lead_id)    REFERENCES leads(id)     ON DELETE SET NULL,
  CONSTRAINT chk_projects_status CHECK (status IN (
    'site visit requested',
    'site visit done',
    'quotation sent',
    'advance received',
    'work started',
    'work completed',
    'completed',
    'rejected'
  )),
  CONSTRAINT chk_projects_completion CHECK (completion_percent >= 0 AND completion_percent <= 100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE milestones (
  id             char(36)     NOT NULL,
  company_id     char(36)     NOT NULL,
  project_id     char(36)     NOT NULL,
  title          varchar(255) NOT NULL,
  milestone_date date         NOT NULL,
  comments       text         DEFAULT NULL,
  created_at     timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_milestones_company_id (company_id),
  KEY idx_milestones_project_id (project_id),
  KEY idx_milestones_date (milestone_date),
  CONSTRAINT fk_milestones_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_milestones_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE vendors (
  id             char(36)     NOT NULL,
  company_id     char(36)     NOT NULL,
  name           varchar(255) NOT NULL,
  phone          varchar(50)  DEFAULT NULL,
  email          varchar(255) DEFAULT NULL,
  gst_number     varchar(32)  DEFAULT NULL,
  address        text         DEFAULT NULL,
  website        varchar(512) DEFAULT NULL,
  bank_account_holder varchar(255) DEFAULT NULL,
  bank_name           varchar(255) DEFAULT NULL,
  bank_account_number varchar(64)  DEFAULT NULL,
  bank_ifsc           varchar(32)  DEFAULT NULL,
  bank_address        text         DEFAULT NULL,
  created_at     timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at     timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_vendors_company (company_id),
  CONSTRAINT fk_vendors_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE vendor_contacts (
  id         char(36)     NOT NULL,
  company_id char(36)     NOT NULL,
  vendor_id  char(36)     NOT NULL,
  name       varchar(255) NOT NULL,
  phone      varchar(50)  DEFAULT NULL,
  email      varchar(255) DEFAULT NULL,
  tag        varchar(32)  NOT NULL DEFAULT 'contact_person',
  tag_label  varchar(255) DEFAULT NULL,
  sort_order int          NOT NULL DEFAULT 0,
  created_at timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_vendor_contacts_vendor (vendor_id),
  KEY idx_vendor_contacts_company (company_id),
  CONSTRAINT fk_vendor_contacts_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_vendor_contacts_vendor FOREIGN KEY (vendor_id) REFERENCES vendors(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE chemicals (
  id              char(36)     NOT NULL,
  company_id      char(36)     NOT NULL,
  name            varchar(255) NOT NULL,
  unit_of_measure varchar(32)  NOT NULL DEFAULT 'kg',
  created_at      timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_chemicals_company (company_id),
  CONSTRAINT fk_chemicals_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE vendor_pricing (
  id             char(36)       NOT NULL,
  company_id     char(36)       NOT NULL,
  vendor_id      char(36)       NOT NULL,
  chemical_id    char(36)       NOT NULL,
  price          decimal(12, 4) NOT NULL,
  effective_date date           NOT NULL,
  created_at     timestamp      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at     timestamp      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_vendor_chemical_date (vendor_id, chemical_id, effective_date),
  KEY idx_vp_lookup (vendor_id, chemical_id, effective_date),
  KEY idx_vp_company (company_id),
  CONSTRAINT fk_vp_company  FOREIGN KEY (company_id)  REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_vp_vendor   FOREIGN KEY (vendor_id)   REFERENCES vendors(id)   ON DELETE CASCADE,
  CONSTRAINT fk_vp_chemical FOREIGN KEY (chemical_id) REFERENCES chemicals(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE expenses (
  id                char(36)       NOT NULL,
  company_id        char(36)       NOT NULL,
  project_id        char(36)       NOT NULL,
  expense_type      varchar(32)    NOT NULL DEFAULT 'other',
  vendor_id         char(36)       DEFAULT NULL,
  amount            decimal(12, 2) NOT NULL,
  description       text           DEFAULT NULL,
  expense_date      date           NOT NULL,
  created_at        timestamp      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_expenses_company_id   (company_id),
  KEY idx_expenses_project_id   (project_id),
  KEY idx_expenses_expense_date (expense_date),
  KEY idx_expenses_vendor (vendor_id),
  CONSTRAINT fk_expenses_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_expenses_project FOREIGN KEY (project_id) REFERENCES projects(id)  ON DELETE CASCADE,
  CONSTRAINT fk_expenses_vendor FOREIGN KEY (vendor_id) REFERENCES vendors(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE expense_items (
  id                char(36)       NOT NULL,
  company_id        char(36)       NOT NULL,
  expense_id        char(36)       NOT NULL,
  chemical_id       char(36)       DEFAULT NULL,
  custom_name       varchar(255)   DEFAULT NULL,
  unit_price        decimal(12, 4) NOT NULL DEFAULT 0,
  quantity          decimal(12, 4) NOT NULL DEFAULT 0,
  line_total        decimal(12, 2) NOT NULL DEFAULT 0,
  vendor_pricing_id char(36)       DEFAULT NULL,
  sort_order        int            NOT NULL DEFAULT 0,
  created_at        timestamp      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_expense_items_expense (expense_id),
  KEY idx_expense_items_company (company_id),
  CONSTRAINT fk_expense_items_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_expense_items_expense FOREIGN KEY (expense_id) REFERENCES expenses(id) ON DELETE CASCADE,
  CONSTRAINT fk_expense_items_chemical FOREIGN KEY (chemical_id) REFERENCES chemicals(id) ON DELETE SET NULL,
  CONSTRAINT fk_expense_items_vp FOREIGN KEY (vendor_pricing_id) REFERENCES vendor_pricing(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE payments (
  id              char(36)       NOT NULL,
  company_id      char(36)       NOT NULL,
  project_id      char(36)       NOT NULL,
  payment_method  varchar(32)    NOT NULL DEFAULT 'cash',
  amount          decimal(12, 2) NOT NULL,
  payment_date    date           NOT NULL,
  comments        text           DEFAULT NULL,
  created_at      timestamp      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_payments_company_id   (company_id),
  KEY idx_payments_project_id   (project_id),
  KEY idx_payments_payment_date (payment_date),
  CONSTRAINT fk_payments_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_payments_project FOREIGN KEY (project_id) REFERENCES projects(id)  ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE lenders (
  id         char(36)     NOT NULL,
  company_id char(36)     NOT NULL,
  name       varchar(255) NOT NULL,
  phone      varchar(50)  DEFAULT NULL,
  address    text         DEFAULT NULL,
  notes      text         DEFAULT NULL,
  created_at timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_lenders_company_id (company_id),
  CONSTRAINT fk_lenders_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE loans (
  id               char(36)       NOT NULL,
  company_id       char(36)       NOT NULL,
  lender_id        char(36)       NOT NULL,
  principal_amount decimal(12, 2) NOT NULL,
  loan_date        date           NOT NULL,
  interest_rate    decimal(8, 4)  NOT NULL DEFAULT 0,
  interest_period  varchar(10)    NOT NULL DEFAULT 'year',
  notes            text           DEFAULT NULL,
  created_at       timestamp      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_loans_company_id (company_id),
  KEY idx_loans_lender_id  (lender_id),
  KEY idx_loans_loan_date  (loan_date),
  CONSTRAINT fk_loans_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_loans_lender  FOREIGN KEY (lender_id)  REFERENCES lenders(id)  ON DELETE RESTRICT,
  CONSTRAINT chk_loans_interest_period CHECK (interest_period IN ('year', 'month'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE loan_repayments (
  id               char(36)       NOT NULL,
  company_id       char(36)       NOT NULL,
  loan_id          char(36)       NOT NULL,
  amount           decimal(12, 2) NOT NULL,
  repayment_date   date           NOT NULL,
  payment_method   varchar(32)    NOT NULL DEFAULT 'cash',
  comments         text           DEFAULT NULL,
  created_at       timestamp      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_loan_repayments_company_id (company_id),
  KEY idx_loan_repayments_loan_id    (loan_id),
  KEY idx_loan_repayments_date       (repayment_date),
  CONSTRAINT fk_loan_repayments_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_loan_repayments_loan    FOREIGN KEY (loan_id)    REFERENCES loans(id)    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE project_types (
  id         char(36)     NOT NULL,
  company_id char(36)     NOT NULL,
  category   varchar(64)  NOT NULL,
  name       varchar(255) NOT NULL,
  is_active  tinyint(1)   NOT NULL DEFAULT 1,
  created_at timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_project_types_company (company_id),
  CONSTRAINT fk_project_types_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT chk_project_types_category CHECK (category IN ('Retrofitting', 'Waterproofing', 'NDT Testing'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE entity_project_types (
  id              char(36)    NOT NULL,
  company_id      char(36)    NOT NULL,
  entity_type     varchar(16) NOT NULL,
  entity_id       char(36)    NOT NULL,
  project_type_id char(36)    NOT NULL,
  created_at      timestamp   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      timestamp   NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_entity_project_type (company_id, entity_type, entity_id, project_type_id),
  KEY idx_ept_entity (company_id, entity_type, entity_id),
  CONSTRAINT fk_ept_company      FOREIGN KEY (company_id)      REFERENCES companies(id)     ON DELETE CASCADE,
  CONSTRAINT fk_ept_project_type FOREIGN KEY (project_type_id) REFERENCES project_types(id) ON DELETE CASCADE,
  CONSTRAINT chk_ept_entity_type CHECK (entity_type IN ('lead', 'project'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE entity_contacts (
  id           char(36)     NOT NULL,
  company_id   char(36)     NOT NULL,
  entity_type  varchar(16)  NOT NULL,
  entity_id    char(36)     NOT NULL,
  client_id    char(36)     NOT NULL,
  is_principal tinyint(1)   NOT NULL DEFAULT 0,
  role         varchar(64)  DEFAULT NULL,
  created_at   timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at   timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_entity_contacts_entity (company_id, entity_type, entity_id),
  CONSTRAINT fk_entity_contacts_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_entity_contacts_client  FOREIGN KEY (client_id)  REFERENCES clients(id)   ON DELETE CASCADE,
  CONSTRAINT chk_entity_contacts_type CHECK (entity_type IN ('lead', 'project'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE warranties (
  id              char(36)     NOT NULL,
  company_id      char(36)     NOT NULL,
  project_id      char(36)     NOT NULL,
  start_date      date         NOT NULL,
  duration_months int          NOT NULL,
  end_date        date         NOT NULL,
  terms           text         DEFAULT NULL,
  document_path   varchar(255) DEFAULT NULL,
  created_at      timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_warranties_project (project_id),
  CONSTRAINT fk_warranties_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_warranties_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE tasks (
  id           char(36)     NOT NULL,
  company_id   char(36)     NOT NULL,
  entity_type  varchar(16)  DEFAULT NULL,
  entity_id    char(36)     DEFAULT NULL,
  title        varchar(255) NOT NULL,
  task_type    varchar(64)  NOT NULL DEFAULT 'client_call',
  due_date     date         NOT NULL,
  is_completed tinyint(1)   NOT NULL DEFAULT 0,
  notes        text         DEFAULT NULL,
  created_at   timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at   timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_tasks_due (company_id, due_date),
  KEY idx_tasks_entity (company_id, entity_type, entity_id),
  CONSTRAINT fk_tasks_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT chk_tasks_entity_type CHECK (entity_type IS NULL OR entity_type IN ('lead', 'project'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE audit_logs (
  id         char(36)     NOT NULL,
  company_id char(36)     NOT NULL,
  user_id    char(36)     NOT NULL,
  table_name varchar(64)  NOT NULL,
  record_id  char(36)     NOT NULL,
  action     varchar(16)  NOT NULL,
  details    json         DEFAULT NULL,
  created_at timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_audit_company_date (company_id, created_at),
  CONSTRAINT fk_audit_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_audit_user    FOREIGN KEY (user_id)    REFERENCES users(id)     ON DELETE CASCADE,
  CONSTRAINT chk_audit_action CHECK (action IN ('INSERT', 'UPDATE', 'DELETE'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE document_templates (
  id            char(36)     NOT NULL,
  company_id    char(36)     NOT NULL,
  template_type varchar(32)  NOT NULL,
  file_path     varchar(255) NOT NULL,
  is_active     tinyint(1)   NOT NULL DEFAULT 1,
  created_at    timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_doc_templates_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT chk_doc_template_type CHECK (template_type IN ('quotation', 'receipt', 'warranty'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE generated_documents (
  id            char(36)     NOT NULL,
  company_id    char(36)     NOT NULL,
  project_id    char(36)     NOT NULL,
  template_type varchar(32)  NOT NULL,
  file_path     varchar(255) NOT NULL,
  generated_by  char(36)     NOT NULL,
  created_at    timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_gen_docs_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_gen_docs_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
  CONSTRAINT fk_gen_docs_user    FOREIGN KEY (generated_by) REFERENCES users(id)     ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE leads
  ADD CONSTRAINT fk_leads_project FOREIGN KEY (converted_project_id) REFERENCES projects(id) ON DELETE SET NULL;

-- ── Seed the super admin (run AFTER you have signed up once) ──────────────────
-- Replace the email, then run ONE of these in phpMyAdmin:
--
-- If the user already has a profile (e.g. after "Skip for now"):
--   UPDATE profiles SET role = 'super_admin', is_active = 1, company_id = NULL
--   WHERE id = (SELECT id FROM users WHERE email = 'you@example.com');
--
-- If the user has no profile row yet:
--   INSERT INTO profiles (id, company_id, role, is_active, email)
--   SELECT id, NULL, 'super_admin', 1, email FROM users WHERE email = 'you@example.com';
--
-- Super admins may have a NULL company_id. Use the Admin page and sidebar
-- company switcher to view each company's data, or leave unset to see all.
--
-- Existing DBs: migrate to B2B/B2C model
--   CREATE TABLE customer_accounts (...);  -- copy from schema above
--   ALTER TABLE clients
--     ADD COLUMN customer_account_id char(36) DEFAULT NULL AFTER client_type,
--     ADD COLUMN contact_title varchar(255) DEFAULT NULL AFTER name,
--     ADD KEY idx_clients_customer_account_id (customer_account_id),
--     ADD CONSTRAINT fk_clients_customer_account FOREIGN KEY (customer_account_id)
--       REFERENCES customer_accounts(id) ON DELETE SET NULL;
--   UPDATE clients SET client_type = 'b2c' WHERE client_type = 'private_client';
--   UPDATE clients SET client_type = 'b2b' WHERE client_type = 'contractor';
--   ALTER TABLE clients MODIFY client_type varchar(32) NOT NULL DEFAULT 'b2c';
--
-- Existing DBs: add expense type
--   ALTER TABLE expenses ADD COLUMN expense_type varchar(32) NOT NULL DEFAULT 'other' AFTER project_id;
--
-- Existing DBs: add payment method and comments
--   ALTER TABLE payments ADD COLUMN payment_method varchar(32) NOT NULL DEFAULT 'cash' AFTER project_id;
--   ALTER TABLE payments ADD COLUMN comments text DEFAULT NULL AFTER payment_date;
