-- Skyline-App database schema (MariaDB / MySQL, multi-tenant)
-- Run against your MariaDB database to build it from scratch.
-- WARNING: this script DROPS all existing app tables and their data.
--
-- Tenant isolation (formerly Postgres RLS) is enforced in the PHP API layer:
-- every query is scoped by company_id derived from the logged-in session.

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS expenses;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS clients;
DROP TABLE IF EXISTS profiles;
DROP TABLE IF EXISTS companies;
DROP TABLE IF EXISTS password_resets;
DROP TABLE IF EXISTS users;

SET FOREIGN_KEY_CHECKS = 1;

-- ── Auth ─────────────────────────────────────────────────────────────────────
-- Replaces Supabase auth.users. UUIDs are generated by the PHP layer (v4).

CREATE TABLE users (
  id            char(36)     NOT NULL,
  email         varchar(255) NOT NULL,
  password_hash varchar(255) NOT NULL,
  created_at    timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_users_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE password_resets (
  id         bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id    char(36)     NOT NULL,
  token_hash char(64)     NOT NULL,
  expires_at timestamp    NOT NULL,
  created_at timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_password_resets_token (token_hash),
  KEY idx_password_resets_user  (user_id),
  CONSTRAINT fk_password_resets_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── Tenancy ──────────────────────────────────────────────────────────────────

-- A company is a tenant. Every business row is scoped to one company.
CREATE TABLE companies (
  id         char(36)     NOT NULL,
  name       varchar(255) NOT NULL,
  owner_id   char(36)     NOT NULL,
  created_at timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_companies_owner (owner_id),
  CONSTRAINT fk_companies_owner FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- One profile per user. role + is_active drive access.
CREATE TABLE profiles (
  id         char(36)     NOT NULL,
  company_id char(36)     DEFAULT NULL,
  role       varchar(20)  NOT NULL DEFAULT 'member',
  is_active  tinyint(1)   NOT NULL DEFAULT 1,
  full_name  varchar(255) DEFAULT NULL,
  email      varchar(255) DEFAULT NULL,
  created_at timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_profiles_company_id (company_id),
  CONSTRAINT fk_profiles_user    FOREIGN KEY (id)         REFERENCES users(id)     ON DELETE CASCADE,
  CONSTRAINT fk_profiles_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL,
  CONSTRAINT chk_profiles_role   CHECK (role IN ('super_admin', 'owner', 'member'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── Business tables ──────────────────────────────────────────────────────────

-- CRM: clients/contacts for marketing.
CREATE TABLE clients (
  id         char(36)     NOT NULL,
  company_id char(36)     NOT NULL,
  name       varchar(255) NOT NULL,
  email      varchar(255) DEFAULT NULL,
  phone      varchar(50)  DEFAULT NULL,
  address    text         DEFAULT NULL,
  location   varchar(255) DEFAULT NULL,
  source     varchar(255) DEFAULT NULL,
  tags       json         DEFAULT NULL,
  notes      text         DEFAULT NULL,
  created_at timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_clients_company_id (company_id),
  CONSTRAINT fk_clients_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE projects (
  id                  char(36)       NOT NULL,
  company_id          char(36)       NOT NULL,
  client_id           char(36)       DEFAULT NULL,
  project_title       varchar(255)   NOT NULL,
  client_name         varchar(255)   DEFAULT NULL,
  location            varchar(255)   DEFAULT NULL,
  work_description    text           DEFAULT NULL,
  total_quoted_amount decimal(12, 2) DEFAULT 0,
  amount_received     decimal(12, 2) DEFAULT 0,
  status              varchar(40)    NOT NULL DEFAULT 'site visit requested',
  completion_percent  int            DEFAULT 0,
  start_date          date           DEFAULT NULL,
  end_date            date           DEFAULT NULL,
  created_at          timestamp      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_projects_company_id (company_id),
  KEY idx_projects_client_id  (client_id),
  KEY idx_projects_status     (status),
  KEY idx_projects_start_date (start_date),
  CONSTRAINT fk_projects_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_projects_client  FOREIGN KEY (client_id)  REFERENCES clients(id)   ON DELETE SET NULL,
  CONSTRAINT chk_projects_status CHECK (status IN (
    'site visit requested',
    'site visit done',
    'quotation sent',
    'work started',
    'work completed',
    'completed',
    'rejected'
  )),
  CONSTRAINT chk_projects_completion CHECK (completion_percent >= 0 AND completion_percent <= 100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE expenses (
  id           char(36)       NOT NULL,
  company_id   char(36)       NOT NULL,
  project_id   char(36)       NOT NULL,
  amount       decimal(12, 2) NOT NULL,
  description  text           DEFAULT NULL,
  expense_date date           NOT NULL,
  created_at   timestamp      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_expenses_company_id   (company_id),
  KEY idx_expenses_project_id   (project_id),
  KEY idx_expenses_expense_date (expense_date),
  CONSTRAINT fk_expenses_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_expenses_project FOREIGN KEY (project_id) REFERENCES projects(id)  ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE payments (
  id           char(36)       NOT NULL,
  company_id   char(36)       NOT NULL,
  project_id   char(36)       NOT NULL,
  amount       decimal(12, 2) NOT NULL,
  payment_date date           NOT NULL,
  created_at   timestamp      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_payments_company_id   (company_id),
  KEY idx_payments_project_id   (project_id),
  KEY idx_payments_payment_date (payment_date),
  CONSTRAINT fk_payments_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_payments_project FOREIGN KEY (project_id) REFERENCES projects(id)  ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── Seed the super admin (run AFTER you have signed up once) ──────────────────
-- Replace the email, then run:
--   UPDATE profiles SET role = 'super_admin', is_active = 1
--   WHERE id = (SELECT id FROM users WHERE email = 'you@example.com');
-- A super admin may have a NULL company_id and still sees every company's data.
